system:
  environment: appengine-standard

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

stripeKey:
  devSecretKey: sk_test_51O93vKB6aHGAQTGCjNsNa75J2T8ilFFZpS4a441LBEceglDwUnll3GvpzaeIvCkw6nnWgFxsQY2J34ex4oJjoinm00TmBT4a0b
