# Makefile

open-contract-intellij:
	cd ../vxevents-contract/ && intellij-idea-community .

open-contract-code:
	cd ../vxevents-contract/ && code .

open-web-code:
	cd ../vxevents-web-app-v1 && code .


001-build-contract:
	cd ../vxevents-contract/ && \
	sc-meta

