# Makefile

open-contract-intellij:
	cd ~/workspace/vxbank/vxevents-contract/ && intellij-idea-community .

open-contract-code:
	cd ~/workspace/vxbank/vxevents-contract/ && code .

001-build-contract:
	cd ../vxevents-contract/ && \
	sc-meta

