[package]
name = "vx-events-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.vx-events]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.0"
default-features = false
